name: Static Python Build

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git perl unzip make meson curl tar rsync flex bison
      - name: Build native
        run: make python3 ARCH=x86_64

      - name: Cross-compile aarch64
        run: make python3 ARCH=aarch64

      - name: Cross-compile riscv64
        run: make python3 ARCH=riscv64

      - name: Cross-compile powerpc64
        run: make python3 ARCH=powerpc64

      - name: Package binaries
        run: |
          tar -czf python-static-x86_64.tar.gz python-static-x86_64/
          tar -czf python-static-aarch64.tar.gz python-static-aarch64/
          tar -czf python-static-riscv64.tar.gz python-static-riscv64/
          tar -czf python-static-powerpc64.tar.gz python-static-powerpc64/

      - name: Delete existing release assets
        run: |
          gh release delete-asset binaries python-static-x86_64.tar.gz || true
          gh release delete-asset binaries python-static-aarch64.tar.gz || true
          gh release delete-asset binaries python-static-riscv64.tar.gz || true
          gh release delete-asset binaries python-static-powerpc64.tar.gz || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete release
        run: |
          gh release delete binaries --yes || true
          git push origin :binaries || true

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: binaries
          name: "Latest Static Binaries"
          body_path: .github/workflows/notes.md
          files: |
            python-static-x86_64.tar.gz
            python-static-aarch64.tar.gz
            python-static-riscv64.tar.gz
            python-static-powerpc64.tar.gz
          prerelease: true
